
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- ../../bases/pgpool2

patches:
- path: patches/configmap-pgpool.yaml
  target:
    kind: ConfigMap
    name: APP_INSTANCE-pgpool-configmap

replacements:
- path: replacement.yaml
