apiVersion: apps/v1
kind: Deployment
metadata:
  name: APP_INSTANCE
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  template:
    spec:
      imagePullSecrets:
        - name: APP_NAME_ABB-harbor-pull-secret
      containers:
        - name: APP_INSTANCE
          image: APP_INSTANCE-image
          envFrom:
            - configMapRef:
                name: APP_INSTANCE
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 2
          resources:
            requests:
              memory: "8Mi"
              cpu: "10m"
            limits:
              memory: "100Mi"
              cpu: "100m"
        - name: adapter
          image: nginx/nginx-prometheus-exporter:0.10.0
          args: ["-nginx.scrape-uri", "http://localhost/nginx_status"]
          ports:
            - name: ngmon
              containerPort: 9113
          resources:
            limits:
              memory: 32Mi
              cpu: 40m
            requests:
              memory: 20Mi
              cpu: 20m

