apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    apps.kubernetes.io/component: webapp
    apps.kubernetes.io/instance: APP_INSTANCE
    apps.kubernetes.io/name: APP_NAME
    apps.kubernetes.io/part-of: APP_PART_OF
    logformat: default

resources:
- deployment.yaml
- service-monitor.yaml
- service.yaml
