apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: APP_INSTANCE_DATABASE-datasource
spec:
  allowCrossNamespaceImport: true
  instanceSelector:
    matchLabels:
      dashboards: "edb"
  valuesFrom:
    - targetPath: "user"
      valueFrom:
        secretKeyRef:
          name: "grafanareadonly.APP_INSTANCE_DATABASE.credentials.postgresql.acid.zalan.do"
          key: "username"
    - targetPath: "secureJsonData.password"
      valueFrom:
        secretKeyRef:
          name: "grafanareadonly.APP_INSTANCE_DATABASE.credentials.postgresql.acid.zalan.do"
          key: "password"
  datasource:
    name: ENV-APP_INSTANCE_DATABASE
    type: postgres
    database: postgres
    editable: false
    jsonData:
      connMaxLifetime: 14400
      maxIdleConns: 2
      maxOpenConns: 0
      postgresVersion: 1400
      sslmode: require
      timescaledb: false
    access: proxy
    secureJsonData:
      password: ${password}
    url: APP_INSTANCE_DATABASE.NAMESPACE.svc:5432
    user: ${username}
