apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    app.kubernetes.io/componet: grafana
    app.kubernetes.io/instance: APP_INSTANCE_DATABASE
    app.kubernetes.io/name: APP_NAME
    app.kubernetes.io/part-of: APP_PART_OF

resources:
- grafana-datensource.yaml
