
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
- ../postgres_ha

patches:
- path: patches/postgres.yaml
  target:
    group: acid.zalan.do
    kind: postgresql
    name: APP_INSTANCE-database
    version: v1
