apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    apps.kubernetes.io/component: database
    apps.kubernetes.io/instance: APP_INSTANCE_DATABASE
    apps.kubernetes.io/name: APP_NAME
    apps.kubernetes.io/part-of: APP_PART_OF
    logformat: default

resources:
- postgres.yaml
- podmonitor.yaml
