apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: APP_INSTANCE-podmon-zalando
spec:
  selector:
    matchLabels:
      application: spilo
      app.kubernetes.io/instance: APP_INSTANCE_DATABASE
  podMetricsEndpoints:
  - port: exporter
  podTargetLabels:
    - app.kubernetes.io/component
    - app.kubernetes.io/instance
    - app.kubernetes.io/name
    - app.kubernetes.io/part-of
