
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - ../pooler_ha
  
replacements:
- source:
    fieldPath: data.PGPOOL_PARAMS_BACKEND_HOSTNAME0
    kind: ConfigMap
    name: APP_INSTANCE-pgpool-configmap
  targets:
  - select:
      kind: ConfigMap
      labelSelector: app.kubernetes.io/component=pooler
    fieldPaths:
    - data.PGPOOL_PARAMS_BACKEND_HOSTNAME1
