apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: database-backup
    app.kubernetes.io/instance: APP_INSTANCE_DATABASE-backup
    app.kubernetes.io/name: APP_NAME
    app.kubernetes.io/part-of: APP_PART_OF
    logformat: default

resources:
- secret-clone-job.yaml
- postgres.yaml