apiVersion: batch/v1
kind: Job
metadata:
  name: APP_INSTANCE_DATABASE-secret-clone-job
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      serviceAccountName: sta-secrets-applier-account
      containers:
      - name: APP_INSTANCE_DATABASE-secret-clone-job
        image: bitnami/kubectl:latest
        envFrom:
          - configMapRef:
              name: APP_INSTANCE-envconfig-overlay
        command: ["sh", "-c", "kubectl get secret standby.${APP_INSTANCE_DATABASE}.credentials.postgresql.acid.zalan.do -o yaml |  sed 's/database/&-clone/g' | kubectl apply -f - && kubectl get secret dbadmin.${APP_INSTANCE_DATABASE}.credentials.postgresql.acid.zalan.do -o yaml |  sed 's/database/&-clone/g' | kubectl apply -f - && kubectl get secret postgres.${APP_INSTANCE_DATABASE}.credentials.postgresql.acid.zalan.do -o yaml |  sed 's/database/&-clone/g' | kubectl apply -f -"]
      restartPolicy: Never
  backoffLimit: 4