
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources: 
- ../../bases/backup/wal

patches:
- path: patches/postgres.yaml
  target:
    group: acid.zalan.do
    kind: postgresql
    version: v1
    name: APP_INSTANCE_DATABASE-clone
    labelSelector: logformat=default

replacements:
- path: replacement.yaml
