apiVersion: v1
kind: ConfigMap
metadata:
  name: APP_INSTANCE-pgpool-configmap
data:
  PGPOOL_PARAMS_BACKEND_HOSTNAME0: APP_INSTANCE_DATABASE
  PGPOOL_PARAMS_BACKEND_HOSTNAME1: APP_INSTANCE_DATABASE-repl
  PGPOOL_PARAMS_BACKEND_PORT0: "5432"
  PGPOOL_PARAMS_BACKEND_PORT1: "5432"
  PGPOOL_PARAMS_BACKEND_WEIGHT0: "1"
  PGPOOL_PARAMS_BACKEND_WEIGHT1: "1"
  PGPOOL_PARAMS_BACKEND_FLAG0: ALWAYS_PRIMARY|DISALLOW_TO_FAILOVER
  PGPOOL_PARAMS_BACKEND_FLAG1: DISALLOW_TO_FAILOVER
  PGPOOL_PARAMS_AUTO_FAILBACK: "on"
  PGPOOL_PARAMS_ENABLE_POOL_HBA: "on"
  PGPOOL_PARAMS_SSL: "on"
  PGPOOL_PASSWORD_ENCRYPTION_METHOD: "md5"
  PGPOOL_ENABLE_POOL_PASSWD: "true"
  PGPOOL_SKIP_PASSWORD_ENCRYPTION: "false"
  PGPOOL_PARAMS_SR_CHECK_USER: "postgres"
  PGPOOL_PARAMS_SR_CHECK_PERIOD: "5"
  PGPOOL_PARAMS_NUM_INIT_CHILDREN: "48"
  PGPOOL_PARAMS_MAX_POOL: "2"
