apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    apps.kubernetes.io/component: pooler
    apps.kubernetes.io/instance: APP_INSTANCE-pgpool
    apps.kubernetes.io/name: APP_NAME
    apps.kubernetes.io/part-of: APP_PART_OF
    logformat: pgpool

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
