  - source:
      fieldPath: data.APP_INSTANCE
      kind: ConfigMap
      name: ops-envconfig-overlay
    targets:
    - select:
        kind: Deployment
      fieldPaths:
        - metadata.name
      options:
        delimiter: '-'
        index: 0
    - select:
        kind: GrafanaDatasource
      fieldPaths:
      - metadata.name
      options:
        delimiter: '-'
        index: 0
    - select:
        kind: Service
      reject:
        - labelSelector: app.kubernetes.io/component=ecs
      fieldPaths:
        - metadata.name
      options:
        delimiter: '-'
        index: 0
    - select:
        kind: ServiceMonitor
      fieldPaths:
        - metadata.name
      options:
        delimiter: '-'
        index: 0
    - select:
        kind: PodMonitor
      fieldPaths:
        - metadata.name
      options:
        delimiter: '-'
        index: 0
    - select:
        kind: VirtualServerRoute
      reject:
        - labelSelector: app.kubernetes.io/component=ecs
      fieldPaths:
        - metadata.name
        - spec.upstreams.*.name
        - spec.upstreams.*.service
        - spec.subroutes.*.action.proxy.upstream
      options:
        delimiter: '-'
        index: 0
    - select:
        kind: ConfigMap
        labelSelector: ops=replacement
      fieldPaths:
        - metadata.name
      options:
        delimiter: '-'
        index: 0
    - select:
        kind: ConfigMap
        labelSelector: app.kubernetes.io/component=service
      fieldPaths:
        - metadata.name
        - metadata.labels.[app.kubernetes.io/instance]
        - data.DATABASE__HOST
      options:
        delimiter: '-'
        index: 0
    - select:
        kind: ConfigMap
        labelSelector: app.kubernetes.io/component=pooler
      fieldPaths:
        - metadata.name
      options:
        delimiter: '-'
        index: 0
    - select:
        kind: ConfigMap
        labelSelector: app.kubernetes.io/component=appsettings
      fieldPaths:
        - metadata.name
        - metadata.labels.[app.kubernetes.io/instance]
      options:
        delimiter: '-'
        index: 0
  - source:
      fieldPath: metadata.namespace
      kind: postgresql
      options:
        delimiter: '-'
        index: 0
    targets:
    - select:
        kind: GrafanaDatasource
      fieldPaths:
        - spec.datasource.name
      options:
        delimiter: '-'
        index: 0
    - select:
        kind: postgresql
      fieldPaths:
        - spec.env.[name=WAL_S3_BUCKET].value
      options:
        delimiter: '/'
        index: 1
  - source:
      fieldPath: metadata.namespace
      kind: GrafanaDatasource
    targets:
    - select:
        kind: GrafanaDatasource
      fieldPaths:
        - spec.datasource.url
      options:
        delimiter: '.'
        index: 1
  - source:
      fieldPath: metadata.namespace
      kind: GrafanaDatasource
      options:
        delimiter: '-'
        index: 0
    targets:
    - select:
        kind: GrafanaDatasource
      fieldPaths:
        - spec.datasource.name
      options:
        delimiter: '-'
        index: 0
  - source:
      fieldPath: data.APP_INSTANCE_DATABASE
      kind: ConfigMap
      name: ops-envconfig-overlay
    targets:
    - select:
        kind: postgresql
      fieldPaths:
        - metadata.name
