
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
- ../postgres_ha

patches:
- path: ../../bases/backup/wal/patches/wal-backup-patch.yaml
  target:
    group: acid.zalan.do
    kind: postgresql
    version: v1
    name: APP_INSTANCE_DATABASE
    labelSelector: logformat=default
