
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
- ../postgres_ha
- ../pooler_ha

patches:
- path: patches/postgres-zalando-backup.yaml
  target:
    group: acid.zalan.do
    kind: postgresql
    version: v1
